/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ds1javapoo04082023;

public class App {
    
    public static void main(String[] args) {
        App aplicacao = new App();
        Pessoa p1 = new Pessoa("Mayke");
        Piloto pi1 = new Piloto("Vert Wheeler");
        Carro car = new Carro("Deora II","Scrim Corp.","Brown","750 Cavalos","Fóssil");
        
        System.out.println("Pessoa: "+p1.nome);
        System.out.println("Piloto: "+pi1.nome);
        System.out.println("Veiculo: "+car.nome_carro+" | Fabricante: "+car.fabricante+" | Cor: "+car.cor+" | Potência: "+car.potencia+" | Combustivel: "+car.combustivel);
        
    }
    
}
