/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ds1javapoo04082023;

public class App {
    
    public static void main(String[] args) {
        App aplicacao = new App();
        Pessoa p1 = new Pessoa("Mayke");
        Piloto pi1 = new Piloto("Vert Wheeler");
        NormalCar car = new NormalCar("Kadett","Chevrolet","Prata","110 Cavalos","Fóssil");
        RacingCar carrace = new RacingCar("Deora II","Scrim Corp.","Azul","750 Cavalos","Fóssil","Propulsores a Jato");
        
        System.out.println("Pessoa: "+p1.nome);
        System.out.println("Piloto: "+pi1.nome);
        System.out.println("Carro} Veiculo: "+car.nome_carro+" | Fabricante: "+car.fabricante+" | Cor: "+car.cor+" | Potência: "+car.potencia+" | Combustivel: "+car.combustivel);
        System.out.println("Carro de Corrida} Veiculo: "+carrace.nome_carro+" | Fabricante: "+carrace.fabricante+" | Cor: "+carrace.cor+" | Potência: "+carrace.potencia+" | Combustivel: "+carrace.combustivel+" | Habilidade: "+carrace.hability);
        
    }
    
}
